# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JBeret TCK Testings

on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC
jobs:
  build-test-matrix:
    name: ${{ matrix.jdk-distribution }}-${{ matrix.jdk-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] # bash script only runs on ubuntu
        jdk-distribution: [ temurin ]
        jdk-version: [ '11', '17', '21' ]
        batch-tck-ver: [ '2.1.5' ] # 2.1.1 Can't pass Java 21 tests, so remove it from testing.
        use_branch: [ 'main', '2.1' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk-distribution }} ${{ matrix.jdk-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.jdk-distribution }}
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'
      - name: run setup script
        run: SET_BATCH_TCK_VER=${{ matrix.batch-tck-ver }} USE_BRANCH=${{ matrix.use_branch }} ./run-tck.sh
