# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JBeret TCK Testings Rawhide With The Main Branch Build Of WildFly Preview Server

on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC
  workflow_dispatch:
jobs:
  wildfly-build:
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build.yml@main
    with:
      wildfly-branch: "main"
      wildfly-repo: "wildfly/wildfly"
  build-test-matrix:
    name: ${{ matrix.jdk-distribution }}-${{ matrix.jdk-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: wildfly-build
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] # bash script only runs on ubuntu
        jdk-distribution: [ temurin ]
        jdk-version: [ '21' ]
        use_branch: [ 'main' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: wildfly-maven-repository
          path: .
      - name: Extract WildFly Maven Repo
        shell: bash
        run: |
          tar xvzf wildfly-maven-repository.tar.gz -C ~
      - name: Set up JDK ${{ matrix.jdk-distribution }} ${{ matrix.jdk-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.jdk-distribution }}
          java-version: ${{ matrix.jdk-version }}
          cache: 'maven'
      - name: Run Rawhide Tests With WildFly Preview
        run: USE_PROFILE=provision-preview WFLY_VER=${{needs.wildfly-build.outputs.wildfly-version}} USE_BRANCH=${{ matrix.use_branch }} ./run-tck-rawhide.sh

